### ISSUE TITLE
Добавить favicon и изображения для постинга в соцсети

### ISSUE THREAD

**Issue by Arseniusz** [Arseniusz/radioiceberg#20]

**Comment by smegmaboy** [comment]
опля

[favicon_io.zip](https://github.com/Arseniusz/radioiceberg/files/11956002/favicon_io.zip)

**Comment by Arseniusz** [comment]
Вечером запуляю

**Comment by smegmaboy** [comment]
хуяк

![Image](https://github.com/Arseniusz/radioiceberg/assets/138661525/3017d9d8-437a-4571-89a0-4204ed0a5cc9)
